name: "Swift Doc Coverage"
description: "Generates documentation for your Swift project"

inputs:
  inputs:
    description: "A path to a directory containing Swift (`.swift`) files in your workspace"
    required: true
    default: "./Sources"
  output:
    description: "The path for generated output"
    required: true
    default: "./dcov.json"

runs:
  using: "docker"
  image: "docker://swiftdoc/swift-doc:latest"
  args:
    [
      coverage,
      "${{ inputs.inputs }}",
      --output,
      "${{ inputs.output }}",
    ]

branding:
  icon: "book"
  color: "orange"
